/** \file
 * The SPWaW war cabinet - error handling.
 *
 * Copyright (C) 2005-2016 Erik Cumps <erik.cumps@gmail.com>
 *
 * License: GPL v2
 */

#ifndef	ERROR_H
#define	ERROR_H	1

/* application error codes */
typedef enum e_errorcodes {
	ERR_FAIL = SL_ERR_USER_START,
	ERR_CFG_NOPERSIST,
	ERR_CFG_PATH_NOCWD,
	ERR_CFG_PATH_NOAPP,
	ERR_CFG_PATH_NOUSR,
	ERR_CFG_INCOMPLETE,
	ERR_ARC_OPEN_FAILED,
	ERR_ARC_ITEM_NOTFOUND,
	ERR_ARC_ITEM_LOAD_FAILED,
	ERR_GUI_MAINWINDOW_INIT_FAILED,
	ERR_GUI_ACTION_INIT_FAILED,
	ERR_GUI_MAINMENU_INIT_FAILED,
	ERR_GUI_TOOLBAR_INIT_FAILED,
	ERR_GUI_STATUS_INIT_FAILED,
	ERR_GUI_DOSSIER_INIT_FAILED,
	ERR_GUI_REPORTS_INIT_FAILED,
	ERR_GUI_PLOT_INIT_FAILED,
	ERR_GUI_VIEW_INIT_FAILED,
	ERR_GUI_SMAP_INIT_FAILED,
	ERR_GUI_REPORTS_DOSSIER_INIT_FAILED,
	ERR_GUI_REPORTS_BATTLE_INIT_FAILED,
	ERR_GUI_REPORTS_TURN_INIT_FAILED,
	ERR_GUI_REPORTS_OOB_INIT_FAILED,
	ERR_GUI_REPORTS_ROSTER_INIT_FAILED,
	ERR_GUI_REPORTS_HISTORY_INIT_FAILED,
	ERR_GUI_REPORTS_UNITLIST_INIT_FAILED,
	ERR_GUI_REPORTS_MMAS_INIT_FAILED,
	ERR_APP_INIT_FAILED,
	ERR_STATE_INIT_FAILED,
	ERR_GUI_DLG_LOAD_SAVEGAME_INIT_FAILED,
	ERR_GUI_DLG_LOAD_SNAPSHOT_INIT_FAILED,
	ERR_GUI_DLG_LOAD_DOSSIER_INIT_FAILED,
	ERR_GUI_DLG_EDIT_DOSSIER_INIT_FAILED,
	ERR_GUI_DLG_ABOUT_INIT_FAILED,
	ERR_GUI_ACTION_ERROR,
	ERR_DOSSIER_SETUP_FAILED,
	ERR_DOSSIER_REFRESH_FAILED,
	ERR_DOSSIER_INITLOAD_FAILED,
	ERR_DOSSIER_NEW_FAILED,
	ERR_DOSSIER_NO_FILE,
	ERR_DOSSIER_LOAD_FAILED,
	ERR_DOSSIER_CORRUPT,
	ERR_DOSSIER_SAVE_FAILED,
	ERR_DOSSIER_SAVE_NONAME,
	ERR_DOSSIER_EDIT_FAILED,
	ERR_DOSSIER_ADD_SAVE_FAILED,
	ERR_DOSSIER_ADD_SNAP_FAILED,
	ERR_DOSSIER_DEL_FAILED,
	LAST_ERR_CODE = ERR_DOSSIER_DEL_FAILED
} errorcodes;


/* --- API --- */

SL_ERROR	register_errorcodes	(void);


#endif	/* ERROR_H */
